const checkout = "https://pay.kiwify.com.br/oB9DPRq";
const whatsapp = "https://wa.me/5562981452425";
const benefits = [["800+", "adesivos exclusivos para odontologia"], ["500+", "figurinhas universais para o dia a dia"], ["120+", "sombras e elementos para Stories"], ["Vitalício", "acesso pelo Telegram e Drive"]];
const bonuses = ["Guia de conteúdo estratégico", "Ideias de Stories criativos", "30 fundos prontos para repost", "30 figurinhas para WhatsApp", "Mais de 20 desenhos em PDF", "Vídeos tutoriais e suporte individual"];

export default function Home() {
  return <main>
    <section className="hero"><div className="shell hero-grid">
      <div className="hero-copy"><span className="eyebrow">Pack Stories Harmonie · por Luciana Camelo</span><h1>Transforme os Stories da sua clínica.</h1><p className="lead">Adesivos profissionais, prontos para usar e alinhados à estética da odontologia. Publique com mais agilidade, consistência e personalidade.</p><div className="hero-proof"><strong>+800 adesivos exclusivos</strong><span>Pagamento único · acesso vitalício</span></div><a className="button primary" href={checkout} target="_blank" rel="noreferrer">Quero acessar agora</a><small>Compra segura · garantia de 7 dias</small></div>
      <div className="hero-visual" aria-label="Prévia do Pack Stories Harmonie"><div className="phone phone-back"><img src="/assets/modelo-stories.webp" alt="Exemplo de Story para dentistas"/></div><div className="phone phone-front"><video autoPlay muted loop playsInline preload="metadata" poster="/assets/modelo-stories.webp"><source src="/assets/demo-1.mp4" type="video/mp4"/></video></div><span className="spark one">✦</span><span className="spark two">✦</span></div>
    </div></section>
    <section className="stats shell" aria-label="Resumo do conteúdo">{benefits.map(([value,label])=><article key={value}><strong>{value}</strong><span>{label}</span></article>)}</section>
    <section className="section dark"><div className="shell centered"><span className="eyebrow light">Veja a transformação</span><h2>Stories bonitos sem perder tempo criando do zero</h2><p>Pesquise, baixe — ou simplesmente copie e cole.</p><div className="video-grid">
      <figure><video controls playsInline preload="metadata"><source src="/assets/demo-1.mp4" type="video/mp4"/></video><figcaption>Buscando o adesivo</figcaption></figure>
      <figure><video controls playsInline preload="metadata"><source src="/assets/demo-2.mp4" type="video/mp4"/></video><figcaption>Copiando e colando</figcaption></figure>
      <figure><video controls playsInline preload="metadata"><source src="/assets/demo-3.mp4" type="video/mp4"/></video><figcaption>Criando um Story</figcaption></figure>
    </div></div></section>
    <section className="section shell content-grid"><div className="content-copy"><span className="eyebrow">Tudo organizado para você</span><h2>O que você vai receber</h2><p>Um acervo completo para profissionais de Odontologia e Harmonização Orofacial que desejam se destacar nas redes sociais.</p><ul className="checklist"><li>Mais de 800 adesivos exclusivos</li><li>Mais de 500 adesivos universais</li><li>Pastas organizadas por tópicos</li><li>Acesso via Drive e Telegram</li><li>Pagamento único e acesso vitalício</li><li>Suporte individual pelo WhatsApp</li></ul></div><div className="image-card"><img src="/assets/modelo-stories.webp" alt="Exemplos de adesivos para Stories odontológicos"/></div></section>
    <section className="section soft"><div className="shell centered"><span className="eyebrow">Mais de R$ 150 em bônus</span><h2>8 bônus exclusivos, totalmente grátis</h2><div className="bonus-grid">{bonuses.map((item,i)=><article key={item}><span>{String(i+1).padStart(2,"0")}</span><h3>{item}</h3></article>)}</div></div></section>
    <section className="section shell proof-grid"><div><span className="eyebrow">Clientes reais</span><h2>Quem usa, recomenda</h2><blockquote>“Material de excelente qualidade, nota 10!”</blockquote><p>Suporte próximo e um material pensado para facilitar a rotina da clínica.</p></div><img src="/assets/depoimento.webp" alt="Depoimento de cliente no WhatsApp"/></section>
    <section className="section dark offer"><div className="shell offer-grid"><div><span className="eyebrow light">Oferta especial</span><h2>Pack Stories Harmonie completo</h2><ul className="checklist light-list"><li>+800 adesivos odontológicos</li><li>+500 adesivos universais</li><li>Todos os bônus incluídos</li><li>Acesso vitalício</li></ul></div><div className="price-card"><p>Tudo isso por apenas</p><strong><small>R$</small> 69,90</strong><span>ou 5x de R$ 15,49</span><a className="button primary" href={checkout} target="_blank" rel="noreferrer">Quero meu acesso</a><small>Pagamento único · compra segura</small></div></div></section>
    <section className="section shell guarantee"><div className="seal">7<small>dias</small></div><div><span className="eyebrow">Risco zero</span><h2>Garantia de 7 dias</h2><p>Se o material não atender às suas expectativas, basta solicitar o reembolso dentro do prazo de garantia.</p></div></section>
    <section className="section soft"><div className="shell faq"><div><span className="eyebrow">Dúvidas frequentes</span><h2>Antes de garantir o seu acesso</h2></div><div className="questions"><details><summary>Preciso pagar mais de uma vez?</summary><p>Não. O pagamento é único e o acesso é vitalício.</p></details><details><summary>Como receberei meu pack?</summary><p>Após o pagamento, os dados de acesso são enviados para o e-mail informado na compra.</p></details><details><summary>Como terei acesso às figurinhas?</summary><p>Você encontrará o conteúdo no canal do Telegram e no Drive, dentro da área de membros.</p></details><details><summary>Posso compartilhar ou revender?</summary><p>Não. O material é de uso pessoal; revenda e distribuição são proibidas.</p></details></div></div></section>
    <section className="section shell about"><img src="/assets/luciana.webp" alt="Luciana Camelo"/><div><span className="eyebrow">Quem sou eu?</span><h2>Olá, meu nome é Luciana.</h2><p>Designer e criadora de figurinhas profissionais que transformam seus Stories em uma extensão da sua marca. Cada pack é desenvolvido com carinho, praticidade e atenção à estética.</p><a className="button secondary" href={whatsapp} target="_blank" rel="noreferrer">Falar comigo no WhatsApp</a></div></section>
    <footer><div className="shell"><strong>Pack Stories Harmonie</strong><span>Copyright © 2025 Luciana Camelo · Todos os direitos reservados</span></div></footer><a className="floating" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Falar no WhatsApp">WhatsApp</a>
  </main>;
}
